[package]
name = "boternity-core"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Business logic and repository traits for Boternity"

[dependencies]
boternity-types = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
